title: "My Portfolio"
description: "A showcase of my paintings, photography, and AI-generated art."
baseurl: ""
url: "https://signatartworks.github.io/portfolio"
repository: signatartworks/portfolio
remote_theme: "mmistakes/minimal-mistakes@4.9.0"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5  # Number of posts per page

# Social links (optional)
author:
  name: "Simon Ignat"
