title: "My Portfolio"
description: "A showcase of my paintings, photography, and AI-generated art."
theme: jekyll-theme-cayman
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
