title: "My Portfolio"
description: "A showcase of my paintings, photography, and AI-generated art."
baseurl: ""  # keep this empty for the root directory
url: "https://signatartworks.github.io/portfolio"  # Replace with your actual URL
repository: signatartworks/portfolio
remote_theme: "mmistakes/minimal-mistakes@4.9.0"  # Specifies the theme version

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

paginate: 5  # Number of posts per page

author:
  name: "Simon Ignat"
