title: "My Portfolio"
description: "A showcase of my paintings, photography, and AI-generated art."
remote_theme: "mmistakes/minimal-mistakes@4.9.0" 
show_excerpts: true  # Ensures posts show up with excerpts on the homepage
paginate: 5  # Number of posts per page
paginate_path: "/page:num/"  # Ensures pagination URL paths work correctly
plugins:
  - jekyll-feed
  - jekyll-seo-tag
